"""
Constants and configuration for Bills Tracker application.
"""

# === UI THEME CONSTANTS ===
PRIMARY_COLOR = "#1f538d"
SECONDARY_COLOR = "#4ecdc4"
ACCENT_COLOR = "#ff6b6b"
BACKGROUND_COLOR = "#f7f9fa"
TEXT_COLOR = "#222831"
SUCCESS_COLOR = "#4bb543"
ERROR_COLOR = "#e74c3c"
WARNING_COLOR = "#ffa500"
URGENT_COLOR = "#ff0000"
DISABLED_COLOR = "#b0b0b0"

# === DARK MODE COLORS ===
DARK_BG_COLOR = "#181a20"
DARK_FRAME_BG = "#23262f"
DARK_TEXT_COLOR = "#f1f1f1"
DARK_ENTRY_BG = "#23262f"
DARK_BORDER_COLOR = "#353945"
DARK_PRIMARY_COLOR = "#2563eb"
DARK_LINK_COLOR = "#4e9cff"

# === SPACING CONSTANTS ===
SPACING_XS = 4
SPACING_SM = 8
SPACING_MD = 16
SPACING_LG = 24

# === BUSINESS LOGIC CONSTANTS ===
BILLING_CYCLES = [
    "weekly", "bi-weekly", "monthly", "quarterly", "semi-annually", "annually", "one-time"
]

REMINDER_DAYS = [1, 3, 5, 7, 10, 14, 30]

# === VALIDATION CONSTANTS ===
DATE_FORMAT = '%Y-%m-%d'
MAX_BILL_NAME_LENGTH = 100
MAX_LOGIN_INFO_LENGTH = 200
MAX_PASSWORD_LENGTH = 100
MAX_PHONE_LENGTH = 20
MAX_ACCOUNT_NUMBER_LENGTH = 50
MAX_REFERENCE_ID_LENGTH = 50
MAX_SERVICE_HOURS_LENGTH = 100
MAX_MOBILE_APP_LENGTH = 200

# === REGEX PATTERNS ===
EMAIL_REGEX = r"^[^@\s]+@[^@\s]+\.[^@\s]+$"
PHONE_REGEX = r"^[\d\-\+\(\)\s]+$"

# === PAGINATION CONSTANTS ===
DEFAULT_ITEMS_PER_PAGE = 20
ITEMS_PER_PAGE_OPTIONS = [10, 20, 50, 100]

# === NOTIFICATION CONSTANTS ===
DEFAULT_NOTIFICATION_TIMEOUT = 30  # seconds
DEFAULT_REMINDER_CHECK_INTERVAL = 300  # 5 minutes
SNOOZE_DURATION = 3600  # 1 hour

# === DATABASE CONSTANTS ===
DB_FILE = 'bills_tracker.db'

# === WINDOW CONSTANTS ===
MIN_WINDOW_WIDTH = 800
MIN_WINDOW_HEIGHT = 600
DEFAULT_WINDOW_WIDTH = 1200
DEFAULT_WINDOW_HEIGHT = 800 